import { Paintbrush } from "../types";

export const paintbrushes: Paintbrush[] = [
  {
    itemId: "745",
    name: "Ninja",
    selectionType: "random",
    keywords: ["Ninja pokemon"],
  },
  {
    itemId: "746",
    name: "Lava",
    selectionType: "always",
    keywords: ["Lava Fire Pokemon"],
  },
  {
    itemId: "747",
    name: "Starry",
    selectionType: "always",
    keywords: ["Starry Pokemon"],
  },
  {
    itemId: "748",
    name: "Fossil",
    selectionType: "random",
    keywords: ["Skeleton Pokemon"],
  },
  {
    itemId: "749",
    name: "Electric",
    selectionType: "always",
    keywords: ["Electric Pokemon"],
  },
  {
    itemId: "857",
    name: "Fairy",
    selectionType: "random",
    keywords: ["Fairy Queen Pokemon", "Fairy Winged Pokemon"],
  },
  {
    itemId: "858",
    name: "Magic Knight",
    selectionType: "random",
    keywords: ["Magic Knight Pokemon", "Magic Knight Pokemon with sword"],
  },
  {
    itemId: "859",
    name: "Zombie",
    selectionType: "always",
    keywords: ["Green Zombie Pokemon"],
  },
  {
    itemId: "867",
    name: "Feather",
    selectionType: "always",
    keywords: ["Bird Pokemon"],
  },
  {
    itemId: "868",
    name: "Insect",
    selectionType: "random",
    keywords: ["Stag Beetle Pokemon", "Spider Pokemon", "Bee Pokemon"],
  },
  {
    itemId: "869",
    name: "Berserker",
    selectionType: "always",
    keywords: ["Berserker Pokemon with Axes"],
  },
  {
    itemId: "913",
    name: "Summer",
    selectionType: "always",
    keywords: ["Summer Beach Pokemon"],
  },
  {
    itemId: "914",
    name: "Sea Serpent",
    selectionType: "always",
    keywords: ["Gyarados Serpent Pokemon"],
  },
  {
    itemId: "915",
    name: "Mermaid",
    selectionType: "always",
    keywords: ["Mermaid Pokemon"],
  },
  {
    itemId: "916",
    name: "Surfer",
    selectionType: "always",
    keywords: ["Surfing Pokemon"],
  },
  {
    itemId: "939",
    name: "Leafy",
    selectionType: "random",
    keywords: ["Leafy Nature Pokemon", "Leaf Type Pokemon"],
  },
  {
    itemId: "940",
    name: "Sword Master",
    selectionType: "always",
    keywords: ["Swordmaster Pokemon"],
  },
  {
    itemId: "941",
    name: "Valkyrie",
    selectionType: "always",
    keywords: ["Valkyrie goddess Pokemon"],
  },
  {
    itemId: "947",
    name: "Icy",
    selectionType: "random",
    keywords: ["Icy glacier pokemon", "Frozen pokemon"],
  },
  {
    itemId: "948",
    name: "Sorcerer",
    selectionType: "random",
    keywords: ["Wizard Pokemon", "Wizard Pokemon with Staff"],
  },
  {
    itemId: "949",
    name: "Eldritch",
    selectionType: "always",
    keywords: ["Eldritch Cthulhu Pokemon"],
  },
];
