export const degen = [
  "Cybernetic wolf pokemon with neon fangs",
  "Mutant octopus pokemon with bio-luminescent tentacles",
  "Armored rhino pokemon with missile launchers",
  "Genetically enhanced tiger pokemon with plasma claws",
  "Techno-organic shark pokemon with laser fin",
  "Bionic eagle pokemon with jet-powered wings",
  "Radioactive spider pokemon with glowing web shooters",
  "Mecha-gorilla pokemon with force field generator",
  "Nano-enhanced cheetah pokemon with hypersonic speed",
  "Quantum fox pokemon phasing through dimensions",
  "Battle-ready bear pokemon with titanium claws",
  "Cyber-enhanced cobra pokemon with plasma hood",
  "Mecha-mantis pokemon with laser scythes",
  "Quantum-shifted lion pokemon with void mane",
  "Techno-scorpion pokemon with plasma stinger",
  "Bionic crocodile pokemon with steel-crushing jaws",
  "Cyber-raptor pokemon with missile array",
  "Plasma-core beetle pokemon with energy cannons",
  "Quantum-fused panther pokemon with phase claws",
  "Mecha-hawk pokemon with targeting systems",
  "Wolfbear pokemon with nuclear core",
  "Sharkraptor pokemon with titanium teeth",
  "Spidercrab pokemon with laser web",
  "Liondrake pokemon with plasma breath",
  "Scorpionwolf pokemon with venom cannons",
  "Tigershark pokemon with quantum fins",
  "Eaglebear pokemon with missile talons",
  "Mantisdrake pokemon with energy blades",
  "Cobrascorpion pokemon with dual stingers",
  "Pantherwolf pokemon with void portals",
  "Raptorbat pokemon with sonic scream",
  "Gorillabear pokemon with crushing gauntlets",
  "Spidermantis pokemon with neural web",
  "Hawkdrake pokemon with targeting matrix",
  "Cheetahwolf pokemon with time-slip speed",
  "Octopusbear pokemon with cyber tentacles",
  "Rhinolion pokemon with quantum horn",
  "Tigermantis pokemon with plasma scythes",
  "Scorpioneagle pokemon with missile array",
  "Cobradrake pokemon with venom breath",
];

export const dragon = [
  "Adorable baby Dragon pokemon with sparkly wings",
  "Playful Dragon pokemon hatchling breathing colorful bubbles",
  "Cuddly Dragon pokemon cub with heart-shaped scales",
  "Mischievous Dragon pokemon wyrmling with glowing antennae",
  "Charming Dragon pokemon infant with rainbow-tipped tail",
  "Fluffy cloud Dragon pokemon with cotton candy breath",
  "Bubbly sea Dragon pokemon with coral-shaped horns",
  "Chubby pancake Dragon pokemon with syrup droplet scales",
  "Sleepy Dragon pokemon nestling in a teacup",
  "Giggly lava Dragon pokemon with marshmallow-toasting snout",
  "Bouncy balloon Dragon pokemon floating on heart-shaped wings",
  "Pudgy panda Dragon pokemon with bamboo-pattern scales",
  "Sprinkle-covered cupcake Dragon pokemon with frosting horns",
  "Starry-eyed constellation Dragon pokemon with twinkling scales",
  "Rosy-cheeked apple Dragon pokemon with leaf wings",
  "Bubblegum Dragon pokemon blowing shape-shifting bubbles",
  "Pastel rainbow Dragon pokemon with sherbet-swirl patterns",
  "Plush teddy bear Dragon pokemon with button eyes",
  "Candy cane Dragon pokemon with peppermint-swirl tail",
  "Origami Dragon pokemon with paper-fold texture",
  "Squishy jellybean Dragon pokemon in assorted flavors",
  "Fluffy dandelion Dragon pokemon scattering wishful seeds",
  "Dewy leaf Dragon pokemon with morning mist breath",
  "Gummy bear Dragon pokemon bouncing on jelly wings",
  "Snowflake Dragon pokemon with icy crystal patterns",
  "Cotton candy Dragon pokemon with sugar-spun mane",
  "Bubble tea Dragon pokemon with tapioca pearl scales",
  "Strawberry shortcake Dragon pokemon with whipped cream frills",
  "Sunflower Dragon pokemon with petal-shaped scales",
  "Chocolate chip cookie Dragon pokemon with melty spots",
  "Watermelon Dragon pokemon with seed-shaped markings",
  "Honey bee Dragon pokemon with fuzzy striped body",
  "Lullaby Dragon pokemon singing sweet melodies",
  "Crayon Dragon pokemon coloring its own scales",
  "Soap bubble Dragon pokemon reflecting rainbow hues",
  "Pinwheel Dragon pokemon spinning in the breeze",
  "Popsicle Dragon pokemon melting sweet icy treats",
  "Butterfly Dragon pokemon with delicate wing patterns",
  "Ladybug Dragon pokemon with polka-dot shell",
  "Yarn ball Dragon pokemon unraveling colorful strings",
  "Kaleidoscope Dragon pokemon shifting geometric patterns",
  "Lemon drop Dragon pokemon with sour-sweet expressions",
  "Pinata Dragon pokemon filled with candy surprises",
  "Jigsaw puzzle Dragon pokemon with interlocking pieces",
  "Sticker book Dragon pokemon covered in cute decals",
  "Finger paint Dragon pokemon with messy artistic splotches",
  "Rubber ducky Dragon pokemon floating in bubble baths",
  "Lollipop Dragon pokemon swirling with fruity flavors",
  "Pillow fort Dragon pokemon guarding blanket castles",
  "Kitten-Dragon pokemon hybrid with fluffy scales",
  "Puppy-Dragon pokemon with wagging flame tail",
  "Bunny-Dragon pokemon with floppy ear wings",
  "Panda-Dragon pokemon with bamboo horns",
  "Duckling-Dragon pokemon paddling in a teacup",
  "Piglet-Dragon pokemon with curly tail and snout",
  "Penguin-Dragon pokemon sliding on icy wings",
  "Hamster-Dragon pokemon with puffy cheek fire sacs",
  "Koala-Dragon pokemon hugging eucalyptus branch",
  "Otter-Dragon pokemon playfully splashing with tail",
];

export const kawaii = [
  "Kawaii hamster pokemon with puffy cheek pouches",
  "Kawaii jellyfish pokemon with starry-tipped tentacles",
  "Kawaii red panda pokemon with bamboo leaf crown",
  "Kawaii alpaca pokemon with rainbow wool tufts",
  "Kawaii axolotl pokemon with crystal gills",
  "Kawaii fennec fox pokemon with glittery giant ears",
  "Kawaii sloth pokemon hugging a crescent moon",
  "Kawaii sugar glider pokemon with sparkly membrane wings",
  "Kawaii quokka pokemon with permanent happy smile",
  "Kawaii capybara pokemon wearing flower necklace",
  "Kawaii platypus pokemon with glowing bill",
  "Kawaii sea otter pokemon floating with starfish",
  "Kawaii tanuki pokemon with leaf-pattern fur",
  "Kawaii pangolin pokemon with crystal scales",
  "Kawaii flying squirrel pokemon with pastel parachute",
  "Kawaii tapir pokemon with dream-catching trunk",
  "Kawaii dumbo octopus pokemon with heart tentacles",
  "Kawaii meerkat pokemon with rainbow guard fur",
  "Kawaii slow loris pokemon with galaxy eyes",
  "Kawaii numbat pokemon with striped fairy wings",
  "Kawaii tardigrade pokemon with rainbow spots",
  "Kawaii kinkajou pokemon with honey-dripping tail",
  "Kawaii jerboa pokemon with bouncy spring legs",
  "Kawaii chinchilla pokemon with cloud-soft fur",
  "Kawaii dik-dik pokemon with crystal antennae",
  "Kawaii caracal pokemon with sparkly ear tufts",
  "Kawaii pine marten pokemon with glowing tail",
  "Kawaii coatimundi pokemon with candy-striped tail",
  "Kawaii elephant shrew pokemon with flower nose",
  "Kawaii binturong pokemon with cotton-candy fur",
  "Kawaii bunnycat pokemon with floating ears",
  "Kawaii pandafox pokemon with bamboo patterns",
  "Kawaii owlbear pokemon with star-speckled wings",
  "Kawaii deerphin pokemon with coral antlers",
  "Kawaii squirrelbee pokemon with honey-filled cheeks",
  "Kawaii hamsterfly pokemon with nectar pouch",
  "Kawaii kittenphant pokemon with ribbon trunk",
  "Kawaii bunnycorn pokemon with carrot horn",
  "Kawaii foxolotl pokemon with crystal frills",
  "Kawaii pandapus pokemon with eight fluffy legs",
  "Kawaii puppyfish pokemon with bubble bark",
  "Kawaii kittenfox pokemon with nine fluffy tails",
  "Kawaii bunnysaur pokemon with flower shell",
  "Kawaii hamsterphin pokemon with water whiskers",
  "Kawaii penguincat pokemon with ice crystal fur",
  "Kawaii otterfly pokemon with rainbow wing fins",
  "Kawaii koalion pokemon with eucalyptus mane",
  "Kawaii rabbiphant pokemon with floppy ear wings",
  "Kawaii pandolphin pokemon with bamboo fins",
  "Kawaii kitterpillar pokemon with rainbow segments",
];
