export const degen = [
  "Crimson heart warrior pokemon with pulsing ruby core",
  "Blood-red cupid pokemon with heart-tipped void arrows",
  "Valentine berserker pokemon with beating heart armor",
  "Heart-core assassin pokemon with ruby blade wings",
  "Crimson love hunter pokemon with heart-shaped missiles",
  "Blood knight pokemon with ruby heart crystals",
  "Heart-forged warrior pokemon with crimson plasma",
  "Ruby-core berserker pokemon with heart-shaped cannons",
  "Valentine phantom pokemon with blood-red heart aura",
  "Crimson heart beast pokemon with ruby targeting",
  "Blood-rose reaper pokemon with heart-shaped scythe",
  "Ruby knight pokemon with heart-core weapons",
  "Valentine ninja pokemon with crimson heart shadows",
  "Heart-core assassin pokemon with ruby rose blades",
  "Blood-red hunter pokemon with heart crystal armor",
];

export const dragon = [
  "Ruby heart dragon pokemon with crystal rose scales",
  "Valentine wyrm pokemon with heart-shaped wings",
  "Blood-red dragon pokemon with ruby heart crystals",
  "Heart crystal dragon pokemon with crimson rose armor",
  "Ruby drake pokemon with valentine heart core",
  "Love dragon pokemon with blood-red heart scales",
  "Heart wyrm pokemon with ruby crystal spines",
  "Valentine serpent pokemon with crimson heart patterns",
  "Ruby rose dragon pokemon with heart crystal wings",
  "Blood-red wyrm pokemon with heart-shaped horns",
  "Heart crystal drake pokemon with ruby scale armor",
  "Valentine dragon pokemon with blood-red heart core",
  "Ruby serpent pokemon with heart-shaped crystals",
  "Love wyrm pokemon with crimson heart patterns",
  "Heart drake pokemon with ruby rose wings",
];

export const kawaii = [
  "Kawaii heart-shaped fairy pokemon with ruby sparkles",
  "Kawaii valentine bunny pokemon shaped like a pink heart",
  "Kawaii heart-bodied kitten pokemon with ruby paws",
  "Kawaii love puppy pokemon with heart-shaped body",
  "Kawaii heart-shaped bear pokemon with ruby bow",
  "Kawaii valentine fox pokemon made of tiny hearts",
  "Kawaii heart-shaped hamster pokemon with rosy cheeks",
  "Kawaii love bird pokemon with heart-shaped body",
  "Kawaii heart-shaped deer pokemon with ruby antlers",
  "Kawaii valentine panda pokemon made of pink hearts",
  "Kawaii heart-shaped sheep pokemon with ruby wool",
  "Kawaii love mouse pokemon with heart-shaped body",
  "Kawaii heart-shaped penguin pokemon with ruby crown",
  "Kawaii valentine seal pokemon made entirely of hearts",
  "Kawaii ruby pokemon shaped like a giant heart",
];
