export const degen = [
  "Cybernetic frost phoenix pokemon with plasma wings",
  "Battle-ready glacier troll pokemon with ice armor",
  "Mutant ice chimera pokemon with void crystals",
  "Quantum winter wraith pokemon with frost venom",
  "Armored arctic griffin pokemon with crystal talons",
  "Techno-enhanced jack frost pokemon with neural frost",
  "Bionic snow queen pokemon with freeze-ray crown",
  "Combat frost imp pokemon with titanium claws",
  "Plasma-core ice elemental pokemon with targeting matrix",
  "Cyber-enhanced winter witch pokemon with void staff",
  "Mecha-frost unicorn pokemon with quantum horn",
  "Battle-ready snow angel pokemon with plasma halos",
  "Techno-ice siren pokemon with sonic crystals",
  "Armored frost gnome pokemon with ice missiles",
  "Quantum snowflake sprite pokemon with crystal core",
  "Cyber-snow leopard pokemon with neural implants",
  "Mecha-polar griffin pokemon with plasma talons",
  "Bionic snow lynx pokemon with cryo-fangs",
  "Combat ice dragon pokemon with frost cannons",
  "Techno-gingerbread pokemon with weapon systems",
];

export const dragon = [
  "Frost Dragon pokemon with ice crystal scales",
  "Winter Dragon pokemon with snowflake patterns",
  "Glacier Dragon pokemon with frozen spikes",
  "Arctic Dragon pokemon with aurora wings",
  "Snow Dragon pokemon with frost-crystal horns",
  "Ice Dragon pokemon with frozen claws",
  "Polar Dragon pokemon with crystal spines",
  "Frost Phoenix Dragon pokemon with ice wings",
  "Winter Wraith Dragon pokemon with frost mist",
  "Snow Queen Dragon pokemon with crystal crown",
  "Ice Elemental Dragon pokemon with frost breath",
  "Glacier Wyrm pokemon with frozen scales",
  "Winter Storm Dragon pokemon with snow clouds",
  "Frost Serpent pokemon with ice fangs",
  "Arctic Drake pokemon with frozen armor",
  "Crystal Dragon pokemon with ice shards",
  "Boreal Dragon pokemon with frost patterns",
  "Tundra Dragon pokemon with frozen spikes",
  "Northern Dragon pokemon with ice crystals",
  "Polar Wyrm pokemon with frost scales",
];

export const kawaii = [
  "Kawaii snow leopard pokemon with crystal spots",
  "Kawaii frost sprite pokemon with snowflake wings",
  "Kawaii ice unicorn pokemon with crystal horn",
  "Kawaii snow angel pokemon with frost halos",
  "Kawaii winter fox pokemon with crystal tails",
  "Kawaii frost imp pokemon with ice crystals",
  "Kawaii gingerbread man pokemon",
  "Kawaii ice phoenix pokemon with frost feathers",
  "Kawaii winter fairy pokemon with snow dust",
  "Kawaii frost kitten pokemon with crystal fur",
  "Kawaii snow bunny pokemon with ice patterns",
  "Kawaii glacier pup pokemon with frost markings",
  "Kawaii ice griffin pokemon with crystal wings",
  "Kawaii winter sprite pokemon with snow swirls",
  "Kawaii frost lynx pokemon with crystal whiskers",
  "Kawaii snow deer pokemon with ice antlers",
  "Kawaii winter owl pokemon with frost wings",
  "Kawaii ice bear pokemon with crystal claws",
  "Kawaii frost wolf pokemon with snow patterns",
  "Kawaii winter phoenix pokemon with ice trails",
];
